import SwiftUI

// MARK: - InspectorPanelView — right panel with contextual content

/// Replicates Kun's right panel modes: todo, changes, browser, file, plan, sdd-ai, subagents.
/// Each mode shows a different view. The panel has a header with the current mode title and close button.
struct InspectorPanelView: View {
    @Environment(ChatStore.self) private var chatStore

    var body: some View {
        VStack(spacing: 0) {
            // Header
            inspectorHeader

            Divider()

            // Content based on mode
            switch chatStore.rightPanelMode {
            case .todo:
                TodoPanelContent()
            case .changes:
                ChangesPanelContent()
            case .browser:
                BrowserPanelContent()
            case .file:
                FilePreviewContent()
            case .plan:
                PlanPanelContent()
            case .sddAI:
                SddAIPanelContent()
            case .subagents:
                SubagentsPanelContent()
            case nil:
                EmptyView()
            }
        }
        .background(.background)
        .frame(minWidth: 280)
    }

    // MARK: - Header

    private var inspectorHeader: some View {
        HStack {
            Text(modeTitle)
                .font(.system(size: 13, weight: .semibold))

            Spacer()

            Button {
                chatStore.rightPanelMode = nil
            } label: {
                Image(systemName: "xmark")
                    .font(.system(size: 11, weight: .medium))
                    .foregroundStyle(.tertiary)
                    .frame(width: 20, height: 20)
                    .background(.quaternary.opacity(0.3), in: Circle())
            }
            .buttonStyle(.borderless)
            .help("Close panel")
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
    }

    private var modeTitle: String {
        switch chatStore.rightPanelMode {
        case .todo: return "To-Do"
        case .changes: return "Changes"
        case .browser: return "Browser"
        case .file: return "File Preview"
        case .plan: return "Plan"
        case .sddAI: return "SDD Assistant"
        case .subagents: return "Sub-agents"
        case nil: return ""
        }
    }
}

// MARK: - Panel Contents

struct TodoPanelContent: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "list.clipboard")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("No to-do items")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Text("Tasks extracted from the conversation will appear here")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct ChangesPanelContent: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "doc.text")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("No changes yet")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Text("File changes from the assistant will be listed here")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct BrowserPanelContent: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "globe")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("Dev Browser")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Text("Preview websites generated by the assistant")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct FilePreviewContent: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "doc.text.magnifyingglass")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("No file selected")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Text("Select a file from the workspace tree or a diff to preview")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct PlanPanelContent: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "clipboard")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("No active plan")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Text("Switch to Plan mode and send a message to generate a plan")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct SddAIPanelContent: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "pencil.and.list.clipboard")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("SDD Assistant")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Text("Open a requirement draft to start working on a software design document")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct SubagentsPanelContent: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "person.2")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("No active sub-agents")
                .font(.subheadline)
                .foregroundStyle(.secondary)
            Text("Delegated tasks and sub-agents will appear here")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}
